import { Rank } from '@/lib/types';

export const MaimaiLevelMap: Readonly<Record<number, string>> = {
    1: '1',
    2: '2',
    3: '3',
    4: '4',
    5: '5',
    6: '6',
    7: '7',
    8: '7+',
    9: '8',
    10: '8+',
    11: '9',
    12: '9+',
    13: '10',
    14: '10+',
    15: '11',
    16: '11+',
    17: '12',
    18: '12+',
    19: '13',
    20: '13+',
    21: '14',
    22: '14+',
    23: '15',
};

export const SYNC_RULES: [string, string][] = [
    ['music_icon_fdxp', 'FDX+'],
    ['music_icon_fdx', 'FDX'],
    ['music_icon_fsp', 'FS+'],
    ['music_icon_fs', 'FS'],
    ['music_icon_sync', 'SYNC'],
];

export const COMBO_RULES: [string, string][] = [
    ['music_icon_app', 'AP+'],
    ['music_icon_ap', 'AP'],
    ['music_icon_fcp', 'FC+'],
    ['music_icon_fc', 'FC'],
];

export const DX_RULES: [string, string][] = [
    ['music_dx', 'dx'],
    ['music_standard', 'std'],
];

export const DIFF_RULES: [string, string][] = [
    ['diff_basic', 'basic'],
    ['diff_advanced', 'advanced'],
    ['diff_expert', 'expert'],
    ['diff_master', 'master'],
    ['diff_remaster', 'remaster'],
];

const RANK_SSS_PLUS: Readonly<Rank> = {
    title: 'SSS+',
    minA: 100.5,
    factor: 0.224,
};

export const RANK_S: Rank = {
    minA: 97.0,
    factor: 0.2,
    title: 'S',
};

export const RANK_DEFINITIONS: ReadonlyArray<Rank> = [
    RANK_SSS_PLUS,
    {
        minA: 100.0,
        factor: 0.216,
        title: 'SSS',
        maxA: 100.4999,
        maxFactor: 0.222,
    },
    {
        minA: 99.5,
        factor: 0.211,
        title: 'SS+',
        maxA: 99.9999,
        maxFactor: 0.214,
    },
    { minA: 99.0, factor: 0.208, title: 'SS' },
    { minA: 98.0, factor: 0.203, title: 'S+', maxA: 98.9999, maxFactor: 0.206 },
    RANK_S,
    {
        minA: 94.0,
        factor: 0.168,
        title: 'AAA',
        maxA: 96.9999,
        maxFactor: 0.176,
    },
    { minA: 90.0, factor: 0.152, title: 'AA' },
    { minA: 80.0, factor: 0.136, title: 'A' },
    {
        minA: 75.0,
        factor: 0.12,
        title: 'BBB',
        maxA: 79.9999,
        maxFactor: 0.128,
    },
    { minA: 70.0, factor: 0.112, title: 'BB' },
    { minA: 60.0, factor: 0.096, title: 'B' },
    { minA: 50.0, factor: 0.08, title: 'C' },
    { minA: 0.0, factor: 0.016, title: 'D' },
];

export const PATTERN_TAG: Readonly<Record<number, string>> = {
    3: '转圈',
    4: '绝赞',
    6: '扫键',
    7: '散打',
    8: '交互',
    9: '反手',
    10: '一笔画',
    // 11: '水',
    1: '错位',
    17: '跳拍',
    18: '纵连',
    19: '爆发',
    20: '拆弹',
    // 13: '诈称',
    23: '定拍',
    24: '大位移',
};

export const PATTERN_TAG_NAMES_CN: string[] = [
    '转圈',
    '绝赞',
    '扫键',
    '散打',
    '交互',
    '反手',
    '一笔画',
    // '水',
    '错位',
    '跳拍',
    '纵连',
    '爆发',
    '拆弹',
    // '诈称',
    '定拍',
    '大位移',
];

export const PATTERN_TAG_NAMES: string[] = [
    'Spinning',
    'Break Section',
    'Swipe',
    'Scatter',
    'Trill',
    'Cross-hand',
    'Chained Slides',
    // 'Overrated',
    'Umiyuri',
    'Swing',
    'Jack',
    'Burst',
    'Deciphering',
    // 'Underrated',
    'Steady Beat',
    'Jump',
];

export const PATTERN_TAG_NUMBERS: Readonly<number[]> = [
    3, 4, 6, 7, 8, 9, 10,
    // 11,
    1, 17, 18, 19, 20,
    // 13,
    23, 24,
];

export const EVAL_TAG: Readonly<Record<number, string>> = {
    15: '键盘谱',
    14: '星星谱',
    21: '体力谱',
    16: '底力谱',
    22: '高物量',
};

export const EVAL_TAG_NAMES_CN: string[] = [
    '键盘谱',
    '星星谱',
    '体力谱',
    '底力谱',
    '高物量',
];

export const EVAL_TAG_NAMES: string[] = [
    'Tap-heavy',
    'Slide-heavy',
    'Stamina',
    'Foundation',
    'Dense',
];

export const EVAL_TAG_NUMBERS: Readonly<number[]> = [15, 14, 21, 16, 22];

export const PRISM_PLUS_SONGS: Readonly<string[]> = [
    'False Amber (from the Black Bazaar, Or by A Kervan Trader from the Lands Afar, Or Buried Beneath the Shifting Sands That Lead Everywhere but Nowhere)',
    'Fraq',
    'ウタヒメナイトストーム',
    'Feel The Luv',
    'Supersonic Generation',
    'Zitronectar',
    'きゅびずむ',
    'きゅびびびびずむ',
    'ゆりかご',
    '月光',
    'はいよろこんで',
    'ビビデバ',
    'シカ色デイズ',
    'メズマライザー',
    'ももいろの鍵',
    'のだ',
    'Idoratrize World',
    'Synthesis.',
    '[甘]スイートマジック',
    '[回]ハム太郎とっとこうた',
    '[即]チューリングの跡',
    '[匿]匿名M',
    '[助]メズマライザー',
    'Åntinomiε',
    'もういいよ',
    'モエチャッカファイア',
    'マヌルネコのうた',
    'スナネコのうた',
    '[幸]犬日和。(はっぴー歌唱Ver)',
    'ATLAS RUSH',
    'M@GICAL☆CURE! LOVE ♥ SHOT!',
    'Overjoy ★ OVERDOSE!!',
    'DATAERR0R',
    'あいたい星人',
    'ハオ',
    '概して過誤',
    'Unfinished Epic',
    '忙シー日',
    '好きな惣菜発表ドラゴン',
    '[好]好きな惣菜発表ドラゴン',
    '[譜]好きな惣菜発表ドラゴン',
    '[面]好きな惣菜発表ドラゴン',
    '[発]好きな惣菜発表ドラゴン',
    '[表]好きな惣菜発表ドラゴン',
    '[龍]好きな惣菜発表ドラゴン',
    'FLΛME/FRΦST',
    'Help me, ERINNNNNN!!',
    '超最終鬼畜妹フランドール・S',
    'Destined Marionette',
    '[協]Ultimate taste',
    'MYTH Re：LEASE',
    'クーネル・エンゲイザー',
    'ゼロトーキング',
    '抜錨',
    '[覚]Hainuwele',
    '[逆]WE\'RE BACK!!',
    'なんかノイズにきこえる',
    'うぇいびー',
    'RED',
    'ホラフキパペット',
    'BlackFlagBreaker!!',
    'JIGOKU STATION CENTRAL GATE',
    '㋰責任集合体',
    '三日月ステップ 2023',
    'Lover\'s Trick',
    'IMBRUED:FLUX',
    '砂の函',
    'Amereistr',
    'サウンドプレイヤー',
    'World\'s end BLACKBOX',
    'プリズム△▽リズム',
    'AFTER PANDORA',
    'Xaleid◆scopiX',
    'Ref:rain (for 7th Heaven)',
    'crazy (about you)',
    'Drivessover',
    'Tidal Wave',
    '∀',
    'Pixel Galaxy',
    'MIRA',
    '空回りライブラリ',
    'お呪い',
    'ありきたりな恋の歌',
    '[協]Seyana. ～何でも言うことを聞いてくれるアカネチャン～',
    '[耐]星界ちゃんと可不ちゃんのおつかい合騒曲',
    '[騒]ありきたりな恋の歌',
    '少女レイ',
    '少女A',
    '帝国少女',
    'NO ONE YES MAN',
    'Leave All Behind',
    'Retribution ～ Cycle of Redemption ～',
    'Luminescence',
];

export const CIRCLE_SONGS: Readonly<string[]> = [
    '怪盗Rのテーマ',
    'BAD∞END∞NIGHT',
    'チルノのパーフェクトさんすう教室',
    'Magical Flavor',
    'CiRCLE CAMPAiGN',
    'Magical Paradox',
    '殿ッ！？ご乱心！？',
    'イーヴィルガール',
    'Dazzle hop',
    'Unwelcome School',
    '彩りキャンバス',
    '死ぬな！',
    'どんぐりGAME',
    '君だったから',
    'Overdose',
    'Bring it on',
    'モニタリング',
    'テトリス',
    '有頂天ドリーマーズ',
    'Eureka',
    'ニルヴの心臓',
    'サイエンス',
    'エンジェル ドリーム',
    'Hurtling Boys',
    'しゅ～しん？変身☆ハカイシンzzZ',
    '命テステス',
    '拝啓、最高の思い出たち',
    'おべんきょうたいむ',
    'るろうらんる',
    '廃墟にいますキャンペーン',
    'はじまりの未来',
    'Worlders',
    'ヒアソビ',
    '真空都市',
    'Eternal Return',
    'ぱぱぱらビーチ',
    'Get U ♭ack',
    '電光刹歌',
    'ウィーアーピコピコハンマーズ!!!!',
    'ジェットブラック',
    'トレジャーガーデン',
    '最愛人生ランナー',
    '僕は空気が嫁ない',
    'ラストピースに祝福と栄光を',
    '初音ミクの暴走',
    'Let\'s ミクササイズ！！',
    'ミクマリ',
    '雲外蒼電 -Dreaming Voltage-',
    '鬼女紅妖',
    '華天月兎',
    'スノーマン (Rerec)',
    'JINGLE DEATH',
    'ヤミナベ!!!!',
    'み　む　かｩ　わ　ナ　イ　ス　ト　ラ　イ',
    '化けの花',
    'うい麦畑でつかまえて',
    '勝手に生きましょ',
    'アイアイ傘',
    'INTJINTPENTJENTPINFJENFJINFPENFPISTJISFJESTJESFJESTPISTPISFPESFP',
    'Paranoia',
    'Restricted Access',
    '胡蝶乃舞',
    '零號車輛',
    'スローグロー',
    'ECHO,',
    'Phase: Theatre',
    'Sky Trails',
    'ラプラスショコラ',
    '恋の氷結おてんば湯けむりチルノ温泉',
    'イタ電はやめて！ ぼくらのスカーレット・コール',
    'むしみこうにゃーのハッピッピー',
    '7 Wonders',
    'Break The Speakers',
    'Galaxy Blaster',
    'Customized Justice',
];
