[package]
name = "acidbot-api-v2"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.53.1", features = ["full"] } # async runtime
vercel_runtime = { version = "2.4.0", features = ["axum"] } # handles communicating with Vercel's function bridge
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
axum = "0.8.9"
tower = "0.5.3"

[[bin]]
name = "axum"
path = "api/axum.rs"

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = 3
